-- Migration: Add Offline Mode Support to Transactions
-- Date: 2026-02-12
-- Description: Add client_generated_id for idempotency, offline_receipt_number for temporary receipts, and synced_at timestamp

-- Add new columns to transactions table
ALTER TABLE transactions 
ADD COLUMN IF NOT EXISTS client_generated_id UUID,
ADD COLUMN IF NOT EXISTS offline_receipt_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE;

-- Add unique constraint on client_generated_id (for idempotency)
ALTER TABLE transactions 
ADD CONSTRAINT transactions_client_generated_id_unique UNIQUE (client_generated_id);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_transactions_client_generated_id ON transactions(client_generated_id);
CREATE INDEX IF NOT EXISTS idx_transactions_offline_receipt_number ON transactions(offline_receipt_number);
CREATE INDEX IF NOT EXISTS idx_transactions_synced_at ON transactions(synced_at);

-- Add comment to explain the columns
COMMENT ON COLUMN transactions.client_generated_id IS 'UUID generated by client for idempotency - prevents duplicate transactions during sync';
COMMENT ON COLUMN transactions.offline_receipt_number IS 'Temporary receipt number used when transaction created offline (format: OFF-YYYYMMDD-xxxx)';
COMMENT ON COLUMN transactions.synced_at IS 'Timestamp when offline transaction was successfully synced to server';
